### ISSUE TITLE
Get Guild Members

### ISSUE THREAD

**Issue by Mythbusters123** [zikeji/node-hypixel#116]
**Is your feature request related to a problem? Please describe.**
I am currently writing a discord bot, and i have already wrote this in java where i could just grab it from the JSON but this is proving more difficult

**Describe the solution you'd like**
There should be an array called `guildMembers` that will have certain methods pretaining to it, such as `getExpHistory` which will return an array where you can grab the data corresponding to the day, `getRank` which returns the rank, and any other feature in that area

**Describe alternatives you've considered**
I was just pulling from the website, but JSON arrays weren't working for me, so I came here.

**Additional context**
This isnt mandatory, and if i learn more about JS/TS ill probably attempt to PR this with my fix :)

**Comment by zikeji** [comment]
This data is already all available on Hypixel's API under the "guild" endpoint. The API endpoint itself is documented here: https://node-hypixel.zikeji.com/api/#/guild/get_guild

My library implements it as well (as it does every known endpoint). You can use any of the 3 parameters.

```typescript
const guild = await client.guild.player("20934ef9488c465180a78f861586b4cf");
```

This would get the guild of the player's UUID you provided.

```typescript
const guild = await client.guild.id("553490650cf26f12ae5bac8f");
```

This would get the guild by the ID of the guild itself.

```typescript
const guild = await client.guild.name("Mini Squid");
```

And this would get the guild by the name itself.

The guild object that Hypixel returns has a property named "members" which is an array of the members of the guilds, their rank, EXP history, and so forth.

```typescript
const guild = await client.guild.id("553490650cf26f12ae5bac8f");
console.log(guild.members[0].expHistory);
console.log(guild.members[0].rank);
```

The above accesses both of datasets you mentioned for the first member of the guild. You can loop over it as well. The result object is also fully typed out so if you have a IDE that uses type definitions you will get autocomplete suggestions and so forth.

![ezgif-1-164aa68c8120](https://user-images.githubusercontent.com/9063612/102156678-06f3a700-3e4c-11eb-919f-40bda1f6bb02.gif)

I will be closing this issue as this is already all available.

**Comment by Mythbusters123** [comment]
Ok thank you!
