### ISSUE TITLE
Suggestion: SkyWars Level/Prestige Info

### ISSUE THREAD

**Issue by woch341** [zikeji/node-hypixel#203]
**Is your feature request related to a problem? Please describe.**
When I was messing around with hypixel-php, getting the SkyWars level and prestige information was pretty simple because of the helper calculators included.

**Describe the solution you'd like**
It would be great if a SkyWars level/prestige info helper was added to node-hypixel. There's already one for Bedwars so one for SkyWars wouldn't hurt :p

**Comment by zikeji** [comment]
Hey @woch341, I've gone ahead and added one. Really just adding helpers as they're requested.



https://node-hypixel.zikeji.com/guide/helpers/skywars/
