### ISSUE TITLE
Add ranked skywars data endpoint

### ISSUE THREAD

**Issue by senoe** [zikeji/node-hypixel#290]
The endpoint was added to the Hypixel API about a week ago and it would be nice if it was added to this API wrapper :p
[https://api.hypixel.net/#tag/Player-Data/paths/~1player~1ranked~1skywars/get](https://api.hypixel.net/#tag/Player-Data/paths/~1player~1ranked~1skywars/get)

**Comment by zikeji** [comment]
Looks like this endpoint was removed in v2, probably merged into the normal endpoint or something.
