### ISSUE TITLE
Add resources/games endpoint

### ISSUE THREAD

**Issue by ghost** [zikeji/node-hypixel#424]
**Is your feature request related to a problem? Please describe.**
I'm working on a stats web app, and I discovered this endpoint[[1]](https://github.com/HypixelDev/PublicAPI/discussions/197#discussioncomment-1047648) that would remove the need for a switch case operator that converts game types and reduce file size.

**Describe the solution you'd like**
It'd be great to have the endpoint added to node-hypixel.

**Comment by zikeji** [comment]
This was added in the 4.0 update.
