### ISSUE TITLE
SkyBlock Personal Vault missing.

### ISSUE THREAD

**Issue by Jforjo** [zikeji/node-hypixel#458]
**Describe the bug**
The type here: https://github.com/zikeji/node-hypixel/blob/main/src/types/Augmented/SkyBlock/ProfileMember.ts#L293 should have `personal_vault_contents` too.

**Expected behaviour**
`personal_vault_contents` should be there.

**Comment by zikeji** [comment]
I've added this to 4.1.4, I've also added a new template type to cover when types are missing that way they don't get mixed up with actual bug reports.
